OLED_ENABLE = yes
OLED_DRIVER = ssd1306
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes
AUDIO_ENABLE = no
MUSIC_ENABLE = no

CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
LAYER_LOCK_ENABLE = yes
REPEAT_KEY_ENABLE = yes
UNICODE_COMMON = yes

SPLIT_KEYBOARD = yes

#HAPTIC FEEBACK
HAPTIC_ENABLE = no
SPLIT_HAPTIC_ENABLE = no

#PER KEY RGB
RGB_MATRIX_ENABLE = no

#COMBO DICTIONARIES
VPATH += keyboards/gboards
